/*********************
* Lab 01 
**********************
* Shreya Ramella 
* 1/25/21
* CMSC 255 Section 003
**********************/
public class Hello {
		public static void main(String[]args) {
			System.out.println("<Shreya Ramella>");
			System.out.println("<Lab 01>");
			System.out.println("<Create and run a Java program>");
			System.out.println("<January 25, 2021>");
			System.out.println("<CMSC 255 Section 003>");
			System.out.println();
		}
}